services:
  chat_server:
    build: .
    container_name: chat_server
    ports:
      - "1609:1609"
    restart: always
    networks:
      - shared-network

networks:
  shared-network:
    external: true

